name: Build And Deploy App Image

on:
  workflow_call:
    inputs:
      image_tag:
        description: "The tag to give to the App image"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      image_tag:
        description: "The tag to give to the App image"
        required: true
        type: string

env:
  IMG: ghcr.io/${{ github.repository_owner }}/shirnia.com
  TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
    
    - name: Downcase IMG
      run: |
        echo "IMG_NAME=${IMG,,}" >>${GITHUB_ENV}

    # https://github.com/docker/metadata-action
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        # list of Docker images to use as base name for tags
        images: |
          ${{ env.IMG_NAME }}
        # Docker tags based on the following events/attributes
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=sha

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/arm64,linux/amd64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    # - name: Build App Image
    #   uses: docker/build-push-action@v4
    #   with:
    #     context: .
    #     platforms: linux/amd64,linux/arm64
    #     provenance: false
    #     file: Dockerfile
    #     tags: ${{ env.IMG_NAME }}:${{ env.TAG }}
    #     # load: true
    #     cache-from: type=gha
    #     push: false

    # - name: Push App Image
    #   uses: docker/build-push-action@v4
    #   with:
    #     context: .
    #     platforms: linux/amd64,linux/arm64
    #     cache-from: type=gha
    #     cache-to: type=gha,mode=max
