name: Build And Deploy App Image

on:
  workflow_call:
    inputs:
      image_tag:
        description: "The tag to give to the App image"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      image_tag:
        description: "The tag to give to the App image"
        required: true
        type: string

env:
  SRC: misc/dev
  IMG: ghcr.io/${{ github.repository_owner }}/shirnia.com
  TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
    
    - name: Downcase IMG
      run: |
        echo "IMG_NAME=${IMG,,}" >>${GITHUB_ENV}

    - name: Build App Image
      uses: docker/build-push-action@v4
      with:
        context: .
        provenance: false
        file: ${{ env.SRC }}/Dockerfile
        tags: ${{ env.IMG_NAME }}:${{ env.TAG }}
        load: true
        cache-from: type=gha
        push: false

    - name: Push App Image
      uses: docker/build-push-action@v4
      with:
        context: .
        provenance: false
        cache-to: type=gha
        file: ${{ env.SRC }}/Dockerfile
        push: true
        tags: ${{ env.IMG_NAME }}:${{ env.TAG }}

    - name: Deploying new image
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: bash ~/deploy.sh
